### PR TITLE
Install and usage instructions in readme

### PR DESCRIPTION
**Pull request by DerZyklop**

### CODE REVIEW

**Comment by DerZyklop** [comment]
I thought this would be the way to use it. But the `"rules": { … }` seems to be wrong. 

I tried
```
"prefer-early-return": ["error", {
    "maximumStatements": 1
}],
```

But eslint complains:
`Definition for rule 'prefer-early-return' was not found`

And in my editor, this does not get marked as error:

```typescript
const a  = true;
const b = () : boolean => true;
const c = () : boolean => true;

const foo = () : void => {
  if (a) {
    b();
    c();
  }
};

const bar = () : void => {
  if (a) {
    b();
  }
};
```

I also tried `"@regru/prefer-early-return": "error"`
But eslint complains:
`Definition for rule '@regru/prefer-early-return' was not found`

**Comment by shifteee** [comment]
Everything seems wright. Thank you for clarification

**Comment by DerZyklop** [comment]
As I said: I could not get it running either way. So i still think, that something in my pull-request was wrong. 

Anyway… I switched to eslint-plugin-shopify-lean/prefer-early-return which worked for me.

**Comment by shifteee** [comment]
Yep, my bad 😞 

Following config works as intended:
```javascript
plugins: [
    "@regru/prefer-early-return",
 ],
"rules": {
     "@regru/prefer-early-return/prefer-early-return": "error",
},
```

**Pull request merged**
